package file-operations-plugin

def releasePath = "%WORKSPACE%\Release job";

node {
    agent any
    stages {
        stage('Copy from release job') {
            fileOperations([folderCopyOperation(destinationFolderPath: '', sourceFolderPath: '"%WORKSPACE%\\Release job"')])
        }
        stage('Run tests') {
            cd packages/bin/net20 && nunit3-console.exe "../../../Selenium-automation/bin/Debug/Selenium-automation.dll" --result="../../../TestResult.xml"
        }
        stage('Get test report') {
            nunit "TestResult.xml"
        }
    }
}
