def releasePath = "%WORKSPACE%\Release job";

pipeline {
    agent any 
    stages {
        stage('Get latest version of tests') { 
            steps {
                fileOperations([folderCopyOperation(destinationFolderPath: '', sourceFolderPath: '"%WORKSPACE%\\Release job"')]) 
            }
        }
        stage('Run tests') { 
            steps {
                cd packages/bin/net20 && nunit3-console.exe "../../../Selenium-automation/bin/Debug/Selenium-automation.dll" --result="../../../TestResult.xml" 
            }
        }
        stage('Get report') { 
            steps {
                nunit testResultsPattern: 'TestResults.xml'
            }
        }
    }
}
